Document: vdr-plugin-chanman
Title: Debian vdr-plugin-chanman Manual
Author: <insert document author here>
Abstract: This manual describes what vdr-plugin-chanman is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vdr-plugin-chanman/vdr-plugin-chanman.sgml.gz

Format: postscript
Files: /usr/share/doc/vdr-plugin-chanman/vdr-plugin-chanman.ps.gz

Format: text
Files: /usr/share/doc/vdr-plugin-chanman/vdr-plugin-chanman.text.gz

Format: HTML
Index: /usr/share/doc/vdr-plugin-chanman/html/index.html
Files: /usr/share/doc/vdr-plugin-chanman/html/*.html
